global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # scrape nfsb via App Platform internal networking
  # services can communicate using service name as hostname
  - job_name: 'nfsb'
    static_configs:
      - targets: ['nfsb:8080']
    scrape_interval: 5s
    metrics_path: /metrics
