global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # scrape from staging app
  - job_name: 'nfsb-staging'
    scheme: https
    static_configs:
      - targets: ['nfsb-76rng.onstagingocean.app']
    metrics_path: /metrics

  # scrape nfsb metrics from the host machine (local dev)
  - job_name: 'nfsb'
    static_configs:
      - targets: ['host.docker.internal:9090']

  # if running nfsb serve mode locally
  - job_name: 'nfsb-api'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: /metrics
