global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # scrape from staging nfsb app (gvisor environment)
  - job_name: 'nfsb-staging'
    scheme: https
    static_configs:
      - targets: ['app-without-gvisor-gqteg.onstagingocean.app', 'app-with-gvisor-iyp8d.onstagingocean.app']
    metrics_path: /metrics
    # relabel to add environment info
    relabel_configs:
      - source_labels: [__address__]
        target_label: environment
        replacement: staging
