global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # nfsb with gVisor (App Platform default)
  - job_name: 'nfsb-gvisor'
    scheme: https
    static_configs:
      - targets: ['app-with-gvisor-iyp8d.onstagingocean.app']
    metrics_path: /metrics

  # nfsb without gVisor (App Platform with runtime override)
  - job_name: 'nfsb-native'
    scheme: https
    static_configs:
      - targets: ['app-without-gvisor-gqteg.onstagingocean.app']
    metrics_path: /metrics
